CREATE TABLE IF NOT EXISTS KLANT
(
    ID    INT AUTO_INCREMENT PRIMARY KEY,
    NAAM  VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255)
    );

CREATE TABLE IF NOT EXISTS GEBRUIKER
(
    ID             INT AUTO_INCREMENT PRIMARY KEY,
    GEBRUIKERSNAAM VARCHAR(255) NOT NULL,
    WACHTWOORD     VARCHAR(255) NOT NULL,
    ROL            VARCHAR(50)  NOT NULL,
    CONSTRAINT UQ_GEBRUIKER_GEBRUIKERSNAAM UNIQUE (GEBRUIKERSNAAM)
    );

CREATE TABLE IF NOT EXISTS BESTELLING
(
    ID                  INT AUTO_INCREMENT PRIMARY KEY,
    KLANT_ID            INT         NOT NULL,
    SPELTYPE            VARCHAR(50) NOT NULL,
    MAAND               VARCHAR(50) NOT NULL,
    DATUM_REGISTRATIE   TIMESTAMP   NOT NULL,
    BETAALD             BOOLEAN     NOT NULL,
    MEDEWERKER_ID       INT         NOT NULL,
    LAATSTE_UPDATE      TIMESTAMP,

    CONSTRAINT FK_BESTELLING_KLANT FOREIGN KEY (KLANT_ID)
    REFERENCES KLANT (ID),

    CONSTRAINT FK_BESTELLING_MEDEWERKER FOREIGN KEY (MEDEWERKER_ID)
    REFERENCES GEBRUIKER (ID)
    );
